<div>
    <a href="/admin">🏠 Retour</a>
</div>
<h1>Catégories</h1>
<p>
    <a href="/admin/categories/add">Ajouter une catégorie</a>
</p>
<?php if( !empty($categories) ): ?>
<ul>
    <?php foreach( $categories as $category ): ?>
        <li><?php printf( '<a href="/admin/categories/%1$s">%1$s - %2$s</a>', $category->getId(), $category->getLabel() ) ?></li>
    <?php endforeach ?>
</ul>
<?php else: ?>
    <div>Aucune catégorie définie.</div>
<?php endif ?>