<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><?php

use App\Session;

 echo $title ?></title>
</head>
<body>
    <nav>
        <ul>
            <a href="/">Accueil</a>
            <a href="/contact">Contact</a>
        </ul>
        <?php if (isset($_SESSION['user'])): ?>

            <p>Bonjour <?php //AFFICHER LE PRENOM ET NON depuis le tableau user dans session
            $user = Session::class::get('user');
            echo $user->getFirstname() . ' ' . $user->getLastname();
            
            ?></p>
            <a href="/sign-out" class="deconnexion_top">Déconnexion</a>
        <?php else: ?>
            <a href="sign-up">S'inscrire</a>
            <a href="sign-in">Se connecter</a>
        <?php endif; ?>
    </nav>
