<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><?php

use App\Controller\AuthController;
use App\Session;

 echo $title ?></title>
</head>
<body>
    <nav>
        <ul>
            <a href="/">Accueil</a>
            <a href="/mentions-legales">Mentions-légales</a>
        </ul>
        <?php if (isset($_SESSION['user'])): ?>

            <?php if (AuthController::isAnnouncer())
            {
                echo '<a href="/accommodations/add">Créer une annonce</a>';
                echo '<a href="/accommodations">Mes annonces</a>';
            } ?>


            <p> <?php
            $user = Session::class::get('user');
            echo $user->getFirstname() . ' ' . $user->getLastname();
            ?></p>

            <a href="/sign-out" class="deconnexion_top">Déconnexion</a>
        <?php else: ?>
            <a href="sign-up">S'inscrire</a>
            <a href="sign-in">Se connecter</a>
            <a href="accommodations">Annonces</a>
        <?php endif; ?>
    </nav>
