<div>
    <a href="/accommodations">🔙 Retour</a>
</div>
<?php


    ?>
    <h1><?php printf('Location : %s', $accommodation->getTitle()) ?></h1>
    <h2>Détails</h2>
    <div>
        <?php


        //Afficher les informations du bien en fonction de l'id récupéré dans l'url


        ?>
        <li>prix : <?php echo $accommodation->getPrice() ?> €</li>
        <li>Surface : <?php echo $accommodation->getSurface() ?> m²</li>
        <li>Description : <?php echo $accommodation->getDescription() ?></li>
        <li>Capacité : <?php echo $accommodation->getCapacity() ?> voyageur(s)</li>
        <li>Propriétaire : <?php printf($accommodation->getOwner()->getFirstname() . ' ' . $accommodation->getOwner()->getLastname()) ?></li>
        <li>Type de bien : <?php echo $accommodation->getType()->getLabel() ?></li>
        <li>Rue : <?php echo $accommodation->getAddress()->getStreet() ?></li>
        <li>Ville : <?php echo $accommodation->getAddress()->getCity() ?></li>
        <li>Pays : <?php echo $accommodation->getAddress()->getCountry() ?></li>


    </div>