<?php

use App\Model\Entity\Accommodation;
use App\Model\Repository\AccommodationRepository;
use App\Model\Repository\RepoManager;

?>

<div>
    <a href="/announcer">🏠 Retour</a>
</div>
<h1>Vos annonces :</h1>
<p>
    List.phtml "views/accommodation/announcer"
</p>
<p>
    <a href="/accommodations/add">Ajouter une annonce</a>
</p>
<div>
    <?php if (!empty($accommodations)) : ?>
        <ul>
            <?php foreach ($accommodations as $accommodation): ?>
                <li>
                    <ul>
                        <li>id : <?php echo $accommodation->getId() ?></li>
                        <li>titre : <?php echo $accommodation->getTitle() ?></li>
                        <li>prix : <?php echo $accommodation->getPrice() ?></li>
                        <li>Surface : <?php echo $accommodation->getSurface() ?></li>
                        <li>Description : <?php echo $accommodation->getDescription() ?></li>
                        <li>Capacité : <?php echo $accommodation->getCapacity() ?></li>
                        <li>Propriétaire : <?php echo $accommodation->getId_owner() ?></li>
                        <li>Type de bien : <?php echo $accommodation->getId_Type() ?></li>
                        <li>ID Adresse : <?php echo $accommodation->getId_address() ?></li>
                        <div>
                            <?
                            // //Récupérer number_street, street, city, country en recherchant par l'id de id_address de la table accommodation
                            // $repoManager = new RepoManager();
                            // $accommodationRepository = $repoManager->getAccommodationRepo();
                            // $address = $accommodationRepository->findAddressById($accommodation->getId_address());



                            ?>
                        </div>
                    </ul>
                </li>
            <?php endforeach ?>
        </ul>
</div>
<?php else: ?>
    <div>Aucune location enregistrée</div>
<?php endif ?>

