<div>
    <a href="/">🏠 Retour</a>
</div>
<h1>Réservations</h1>
<p>
    <a href="/reservations/add">Créer une réservation</a>
</p>
<?php if (!empty($reservations)): ?>
    <ul>
        <?php foreach ($reservations as $reservation): ?>
            <li>
                <a href="/reservations/<?= $reservation->getId() ?>">
                    <div>
                        <p><?php echo $reservation->getAccommodation($reservation->getId_accommodation())->getTitle(); ?></p>
                        <p><?php printf($reservation->getDateFrom() . ' au ' . $reservation->getDateTo()) ?></p>
                    </div>
                </a>
            </li>
        <?php endforeach ?>
    </ul>
<?php else: ?>
    <div>Aucune réservation enregistrée.</div>
<?php endif ?>