<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Une erreur est survenue - Autodingo.com</title>
</head>
<body>
    <h1>Erreur serveur - 500</h1>
    <p>
        Nous avons rencontré une erreur et nous nous en excusons pour la gêne occasionnée.
    </p>   
    <p>
        Nous mettons tout en oeuvre pour y remédier rapidement.
    </p>
</body>
</html>