<div>
    <a href="/announcer/accommodations/list">🔙 Retour</a>
</div>
<h1>Ajouter un nouvel hébergement</h1>
<form action="/announcer/accommodations" method="post" novalidate>
    <div>
        <label for="input-title">Titre :</label>
        <input type="text" name="title" id="input-title">
    </div>
    <div>
        <label for="input-price">Prix :</label>
        <input type="number" name="price" id="input-price">
    </div>
    <div>
        <label for="input-surface">Surface en mètre carré :</label>
        <input type="number" name="surface" id="input-surface">
    </div>
    <div>
        <label for="input-description">Description du bien:</label>
        <input type="text" name="description" id="input-description">
    </div>
    <div>
        <label for="input-capacity">Capacité du bien en personne :</label>
        <input type="number" name="capacity" id="input-dapacity">
    </div>
    

    <!-- Insérer une liste déroulante pour sélectionner 1 seule choix récupéré depuis la table "accommodation_types" -->
    <div>
        <label for="select-id_type">Type de bien :</label>
        <select name="id_type" id="select-id_type">
            <option value="">Choisissez...</option>
            <!-- Insertion des éléments des équipements -->
            <?php foreach ($accommodation_types  as $type) : ?>
                <option value="<?= $type->getId() ?>"><?= $type->getLabel() ?></option>
            <?php endforeach; ?>
        </select>
            </div>

            <!-- Liste en case à cocher des éléments possible d'ajouter depuis la table equipment -->
             




    <div>
        <input type="submit" value="Ajouter">
    </div>
</form>


<!-- 

TODO: BONUS Si l'on veut rajouter des images :
         
        <div>
        <label for="input-image">Image :</label>
        TODO: Gérer l'upload d'image avec un input de type "file"
        <input type="text" name="image" id="input-image">
    </div>
        -->