<div>
    <a href="/admin">🏠 Retour</a>
</div>
<h1>Voitures</h1>
<p>
    <a href="/accommodation/announcer/add">Ajouter une annonce</a>
</p>
<?php if( !empty($cars) ): ?>
<ul>
    <?php foreach( $cars as $car ): ?>
        <li><?php printf( '<a href="/admin/cars/%1$s">%1$s - %2$s</a>', $car->getId(), $car->getLabel() ) ?></li>
    <?php endforeach ?>
</ul>
<?php else: ?>
    <div>Vous n'avez aucune annonce enregistrée.</div>
<?php endif ?>