<div>
    <a href="/announcer">🏠 Retour</a>
</div>
<h1>Annonces</h1>
<p>
    List.phtml "views/accommodation/announcer"
</p>
<p>
    <a href="/announcer/accommodations/add">Ajouter une annonce</a>
</p>
<?php if( !empty($accommodation) ): ?>
<ul>
    <?php foreach( $accommodations as $accommodation ): ?>
        <li><?php printf( '<a href="/announcer/accommodations/%1$s">%1$s - %2$s</a>', $accommodation->getId(), $accommodation->getLabel() ) ?></li>
    <?php endforeach ?>
</ul>
<?php else: ?>
    <div>Vous n'avez aucune annonce enregistrée.</div>
<?php endif ?>