<p>TODO: Ajouter l'insertion en BDD, sécuriser les datas</p>

<div>
    <a href="/">🔙 Retour</a>
</div>
<h1>Me créer un compte</h1>
<form action="/sign-up/add" method="post" novalidate>
    <div>
        <label for="input-email">Email :</label>
        <input type="email" name="email" id="input-email">
    </div>
    <div>
        <label for="input-password">Mot de passe :</label>
        <input type="password" name="password" id="input-password">
    </div>
    <div>
        <label for="input-lastname">Nom :</label>
        <input type="text" name="lastname" id="input-lastname">
    </div>
    <div>
        <label for="input-firstname">Prénom :</label>
        <input type="text" name="firstname" id="input-firstname">
    </div>
    <div>
        <label for="input-phone">Téléphone :</label>
        <input type="tel" name="phone_number" id="input-phone">
    </div>
    <div>
        <label for="input-role">Rôle :</label>
        <select name="role" id="input-role">
            <option value="">Choisissez...</option>
            <option value="1">Utilisateur</option>
            <option value="2">Annonceur</option>
        </select>
    </div>
    <div>
        <input type="submit" value="Ajouter">
    </div>
</form>