<div>
    <a href="/admin/users">🔙 Retour</a>
</div>
<h1>Modifier</h1>
<form action="/admin/users/<?php echo $user->getId() ?>" method="post" novalidate>
    <div>
        <label for="input-email">Email :</label>
        <input type="email" name="email" id="input-email" value="<?php echo $user->getEmail() ?>">
    </div>
    <div>
        <label for="input-password">Mot de passe :</label>
        <input type="password" name="password" id="input-password" value="<?php echo $user->getPassword() ?>">
    </div>
    <div>
        <label for="input-firstname">Prénom :</label>
        <input type="text" name="firstname" id="input-firstname" value="<?php echo $user->getFirstname() ?>">
    </div>
    <div>
        <label for="input-lastname">Nom :</label>
        <input type="text" name="lastname" id="input-lastname" value="<?php echo $user->getLastname() ?>">
    </div>
    <div>
        <label for="input-phone">Téléphone :</label>
        <input type="tel" name="phone_number" id="input-phone" value="<?php echo $user->getPhoneNumber() ?>">
    </div>
    <fieldset>
        <legend>Addresse</legend>
        <input type="hidden" name="address_id" value="<?php echo $user->getAddressId() ?>">
        <div>
            <label for="input-city">Ville :</label>
            <input type="text" name="city" id="input-city" value="<?php echo $user->getAddress()->getCity() ?>">
        </div>
        <div>
            <label for="input-country">Pays :</label>
            <input type="text" name="country" id="input-country" value="<?php echo $user->getAddress()->getCountry() ?>">
        </div>
    </fieldset>
    <div>
        <input type="submit" value="Enregistrer la modification">
    </div>
</form>
<div>
    <a href="<?php printf( '/admin/users/%s/delete', $user->getId() ) ?>">❌ Supprimer</a>
</div>